### ISSUE TITLE
Populate List of Beers

### ISSUE THREAD

**Issue by faizaanshamsi** [greenfieldhq/we_work_for_beer#15]
- [ ] Where are we Seeding this list from
- [ ] If users can update this list, are we validating against anything?

BreweryDB offers a free API that gives you 400 reads a day and unlimited writes. It allows users to edit/update the DB but all edits get verified. Might make sense to go with them since we could present an interface to their wiki on our site and not have to worry about seeding/validating beers. For commercial use they charge $6/mo and provide unlimited requests.

**Comment by HeroicEric** [comment]
Already have an api key for untappd. Going to use that to autocomplete info later but we was just have them add the info manually for now
